### ISSUE TITLE
Web app no longer working

### ISSUE THREAD

**Issue by murunwas** [nolus-protocol/nolus-core#123]
the web app (https://app.nolus.io) is no longer working, it's displaying this screen for past two days

![image](https://github.com/nolus-protocol/nolus-core/assets/8838943/b16982e2-cd5c-4aab-884d-087a8f0a132b)

**Comment by wwaruaki** [comment]
as far as I see they are updating on the progress and working on resolving the issue. fingers crossed

**Comment by Lockwarr** [comment]
Web app is working, you can follow discord and other channels for post-mortem updates
