### ISSUE TITLE
Create Pipelines for Github

### ISSUE THREAD

**Issue by kostovster** [Nolus-Protocol/nolus-core#25]
- [x] Create protected tags on github
- [x] Create Pipelines for each project
- [ ] ~~Define Policy for 3rd Party Contributors (contribution guideline)~~
- [x] Direct commits in main should be restricted - unless there is an option to restrict to certain account set. In our case the core contributors.
- [ ] ~~Might be good idea to enable dependabot~~

**Comment by gmanev7** [comment]
status update, pipelines of nolus-core and nolus-money-market are done

**Comment by ivivanov** [comment]
explorer has deployment 
webapp has deployment + linting
