### ISSUE TITLE
Multisig Solution for Cosmos Wallets

### ISSUE THREAD

**Issue by kostovster** [Nolus-Protocol/nolus-core#26]
The whole proccess of creating, signing and broadcasting of multisig transaction is described in this artice (ref.: https://jake-hartnell.medium.com/cosmos-sdk-multisigs-96a390a9d3cc ). The only thing is not mentioned here is specifying fees while signing the created transaction with individual keys.

First of all you create a multisig wallet from two or more individual ones with specifying multisig threshold, it controls how many of the keys have to sign in order for a transaction to be valid. After that you can generate a transaction without broadcasting it, redirect output to the file and sign it with keys that participate in the current multisig. When you are done with it you should sign it with the multisig key and finally broadcast your transaction to the chain.

- [x] Check for a UI solution that can be used for the multisig
- [x] host in our repo
- [x] init founa db
- [ ] deploy

**Comment by Lockwarr** [comment]
_**Update**_
Researched the topic and found some projects for multisig UI.
Some of the notable projects that I've saved are:
https://github.com/notional-labs/multisig-ui - https://multisig.notional.ventures/multisigs
https://github.com/cosmos/cosmos-multisig-ui
https://safe.apollo.farm/

I managed to test creating a multisig wallet successfully on the cosmos-hub with https://multisig.notional.ventures/multisigs
However, when I tried to run the project locally with nolus-rila added to the supported projects, I faced some problems when loading data for nolus and could not create multisig wallet 
cc @ivivanov

**Comment by ivivanov** [comment]
_Update_ 
We decided to go with https://github.com/cosmos/cosmos-multisig-ui. Even though it has less UI functionalities it is much cleaner and robust solution without any functional issues.

**Comment by ivivanov** [comment]
_Update_
Closing this issue as it is not part of this project
