### ISSUE TITLE
[ICA] Validate operations on Interchain Accounts at Osmosis

### ISSUE THREAD

**Issue by kostovster** [Nolus-Protocol/nolus-core#31]
The aim is to validate the ability to control accounts on Osmosis from logic implemented as a smart contract on Nolus.
Create an 'ica-demo' smart contract that :
On instantiate, creates an ICA on Osmosis, and keeps track of the result (success/failure/timeout) for subsequent queries of its state. It stores the data necessary for the following operations
On a "Transfer-out" execute message, sends the amount received to the ICA account. Listen to the result and update the balance (member data, not the bank one).
On a "Transfer-in" execute message, sends a message to the ICA account to transfer the given amount back to the 'ica-demo' contract instance. Listen to the result and update the balance (member data, not the bank one).
On a "SwapExactAmountIn" execute message, sends a message to the ICA account to swap the given amount (already transferred) on a given pool using [this](https://docs.osmosis.zone/osmosis-core/modules/gamm/#msgswapexactamountin).
On a "SwapExactAmountOut" execute message, sends a message to the ICA account to swap the given amount (already transferred) for the exact output amount on a given pool using [this](https://docs.osmosis.zone/osmosis-core/modules/gamm/#msgswapexactamountout).

**Comment by gmanev7** [comment]
closing it since the lease contract progressed a lot and it does the validation
